signup2.vue missing end tag ( 這個頁面找不到 end tag ，我找好久還是找不到先推上去)
VueCompilerError:  5
VueCompilerError: Element is missing end tag.
at C:\Users\Tibame_T14\Desktop\project_group\howlegazaiVue\src\views\signup2.vue:5:5